import type { Metadata } from "next";
import { Noto_Serif_Thai, Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import { UiProvider, QueryProvider } from "@/components/providers";

const thaiSans = Noto_Sans_Thai({
  variable: "--font-thai-sans",
  subsets: ["thai"],
});

const notoSerifThai = Noto_Serif_Thai({
  variable: "--font-noto-serif",
  subsets: ["thai"],
  weight: ["100", "200", "300", "400", "500", "600", "700"], // เลือกน้ำหนักที่ต้องการ
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${thaiSans.variable} ${notoSerifThai.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          <UiProvider>{children}</UiProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
